import { AppCode } from '../config';

export default [
  {
    path: `/${AppCode.ResourceManage}/container`,
    name: 'container',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/container/customType`,
        name: 'customType',
        component: '/ResourceManage/Container/CustomContainerType',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/container/management`,
        name: 'management',
        component: '/ResourceManage/Container/ContainerManage',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/container/group`,
        name: 'group',
        component: '/ResourceManage/Container/ContainerGroup',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/container/circulation`,
        name: 'circulation',
        component: '/ResourceManage/Container/ContainerCirculation',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/storage`,
    name: 'storage',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/storage/tote`,
        name: 'tote',
        component: '/ResourceManage/Storage/ToteStorage',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/storage/latentTote`,
        name: 'latentTote',
        component: '/ResourceManage/Storage/LatentToteStorage',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/storage/liftContainer`,
        name: 'liftContainer',
        component: '/ResourceManage/Storage/LiftContainerStorage',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/storage/group`,
        name: 'group',
        component: '/ResourceManage/Storage/StorageGroup',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/storage/delivery`,
        name: 'delivery',
        component: '/ResourceManage/Storage/Delivery',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/agv`,
    name: 'agv',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/agv/registration`,
        name: 'registration',
        component: '/ResourceManage/Agv/AgvRegistration',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/list`,
        name: 'list',
        component: '/ResourceManage/Agv/AgvList',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/group`,
        name: 'group',
        component: '/ResourceManage/Agv/AgvGroup',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/customType`,
        name: 'customType',
        component: '/ResourceManage/Agv/CustomAgvType',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/customIndustrial`,
        name: 'customIndustrial',
        component: '/ResourceManage/Agv/CustomIndustrial',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/faultDefinition`,
        name: 'faultDefinition',
        component: '/ResourceManage/Agv/AgvFaultDefinition',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/faultManagement`,
        name: 'faultManagement',
        component: '/ResourceManage/Agv/AgvFaultManagement',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/OTA`,
        name: 'OTA',
        component: '/ResourceManage/Agv/OTA',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/logDownLoad`,
        name: 'logDownLoad',
        component: '/ResourceManage/Agv/AgvLogDownLoad',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/realTime`,
        name: 'realTime',
        component: '/ResourceManage/Agv/AgvRealTime',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/agv/adapter`,
        name: 'adapter',
        component: '/ResourceManage/Agv/AgvAdapter',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/charger`,
    name: 'charger',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/charger/customType`,
        name: 'customType',
        component: '/ResourceManage/Charger/CustomChargerType',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/registration`,
        name: 'registration',
        component: '/ResourceManage/Charger/ChargeRegistration',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/list`,
        name: 'list',
        component: '/ResourceManage/Charger/ChargeList',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/group`,
        name: 'group',
        component: '/ResourceManage/Charger/ChargerGroup',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/logManagement`,
        name: 'logManagement',
        component: '/ResourceManage/Charger/ChargerLogManagement',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/adapter`,
        name: 'adapter',
        component: '/ResourceManage/Charger/ChargerAdapter',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/faultDefinition`,
        name: 'faultDefinition',
        component: '/ResourceManage/Charger/ChargerFaultDefinition',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/charger/faultManagement`,
        name: 'faultManagement',
        component: '/ResourceManage/Charger/ChargerFaultManagement',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/automation`,
    name: 'automation',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/automation/customType`,
        name: 'customType',
        component: '/ResourceManage/Automation/CustomAutomationType',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/automation/registration`,
        name: 'registration',
        component: '/ResourceManage/Automation/AutomationRegistration',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/automation/list`,
        name: 'list',
        component: '/ResourceManage/Automation/AutomationList',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/automation/logManagement`,
        name: 'logManagement',
        component: '/ResourceManage/Automation/AutomationLogManagement',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/automation/faultDefinition`,
        name: 'faultDefinition',
        component: '/ResourceManage/Automation/AutomationFaultDefinition',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/automation/adapter`,
        name: 'adapter',
        component: '/ResourceManage/Automation/AutomationAdapter',
        authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/integration`,
    name: 'integration',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/integration/webHook`,
        name: 'webHook',
        component: '/ResourceManage/Integration/WebHook/index',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/integration/logManagement`,
        name: 'logManagement',
        component: '/ResourceManage/Integration/IntegrationLogManagement',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/resourceLock`,
    name: 'resourceLock',
    icon: 'environment',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
    routes: [
      {
        path: `/${AppCode.ResourceManage}/resourceLock/targetLock`,
        name: 'targetLock',
        component: '/ResourceManage/ResourceLock/TargetLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/agvLock`,
        name: 'agvLock',
        component: '/ResourceManage/ResourceLock/AgvLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/liftContainerLock`,
        name: 'liftContainerLock',
        component: '/ResourceManage/ResourceLock/LiftContainerLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/toteLock`,
        name: 'toteLock',
        component: '/ResourceManage/ResourceLock/ToteLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/liftContainerStorageLock`,
        name: 'liftContainerStorageLock',
        component: '/ResourceManage/ResourceLock/LiftContainerStorageLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/toteStorageLock`,
        name: 'toteStorageLock',
        component: '/ResourceManage/ResourceLock/ToteStorageLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
      {
        path: `/${AppCode.ResourceManage}/resourceLock/latentToteStorageLock`,
        name: 'latentToteStorageLock',
        component: '/ResourceManage/ResourceLock/LatentToteStorageLock',
        authority: ['ADMIN', 'SUPERMANAGER'],
      },
    ],
  },
  {
    path: `/${AppCode.ResourceManage}/resourceBind`,
    name: 'resourceBind',
    icon: 'environment',
    component: '/ResourceManage/ResourceBind',
    authority: ['ADMIN', 'SUPERMANAGER', 'MANAGER'],
  },
];
