import React from 'react';
import {
  EnvironmentOutlined,
  LockOutlined,
  SettingOutlined,
  CarOutlined,
  WarningOutlined,
  UserOutlined,
  HomeOutlined,
  IeOutlined,
  ApartmentOutlined,
  AndroidOutlined,
  GlobalOutlined,
  PlusOutlined,
  DeleteOutlined,
  FormOutlined,
  RollbackOutlined,
  EditOutlined,
  InboxOutlined,
  ReadOutlined,
  ApiOutlined,
  MediumOutlined,
  NotificationOutlined,
  UsergroupAddOutlined,
  TranslationOutlined,
  CodepenOutlined,
  HistoryOutlined,
  LoadingOutlined,
  ScheduleOutlined,
  ProfileOutlined,
  ShareAltOutlined,
} from '@ant-design/icons';
import { IconFont } from '@/components/IconFont';

export default {
  log: <IconFont type="icon-log" />,
  layout: <IconFont type="icon-layout" />,
  charger: <IconFont type="icon-charger2" />,
  taskManage: <IconFont type="icon-taskManage" />,
  report: <IconFont type="icon-report" />,
  customConfig: <IconFont type="icon-customConfig" />,
  authorize: <IconFont type="icon-authorize" />,
  storage: <IconFont type="icon-storage" />,
  automation: <IconFont type="icon-automation" />,
  binding: <IconFont type="icon-binding" />,
  taskSearch: <IconFont type="icon-taskSearch" />,
  dependency: <IconFont type="icon-dependency" />,
  limit: <IconFont type="icon-limit" />,
  map: <IconFont type="icon-map" />,
  screenReport: <IconFont type="icon-screenReport" />,
  section: <IconFont type="icon-section" />,
  trigger: <IconFont type="icon-trigger" />,
  userRole: <IconFont type="icon-role" />,

  strategy: <ShareAltOutlined />,
  planning: <ScheduleOutlined />,
  executing: <LoadingOutlined />,
  history: <HistoryOutlined />,
  container: <CodepenOutlined />,
  translate: <TranslationOutlined />,
  pool: <ProfileOutlined />,
  environment: <EnvironmentOutlined />,
  lock: <LockOutlined />,
  setting: <SettingOutlined />,
  agv: <CarOutlined />,
  warning: <WarningOutlined />,
  user: <UserOutlined />,
  home: <HomeOutlined />,
  ie: <IeOutlined />,
  apartment: <ApartmentOutlined />,
  android: <AndroidOutlined />,
  global: <GlobalOutlined />,
  plus: <PlusOutlined />,
  delete: <DeleteOutlined />,
  form: <FormOutlined />,
  rollback: <RollbackOutlined />,
  edit: <EditOutlined />,
  inbox: <InboxOutlined />,
  read: <ReadOutlined />,
  api: <ApiOutlined />,
  richEditor: <MediumOutlined />,
  notification: <NotificationOutlined />,
};
