import React from 'react';
import {
  ApiOutlined,
  BellOutlined,
  CarOutlined,
  CodepenOutlined,
  ControlOutlined,
  DeploymentUnitOutlined,
  EnvironmentOutlined,
  ExceptionOutlined,
  FileSearchOutlined,
  FireOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  HistoryOutlined,
  HomeOutlined,
  IeOutlined,
  LockOutlined,
  MediumOutlined,
  MessageOutlined,
  PaperClipOutlined,
  ProfileOutlined,
  ProjectOutlined,
  ScheduleOutlined,
  ShareAltOutlined,
  ThunderboltOutlined,
  TranslationOutlined,
  UnorderedListOutlined,
  UserOutlined,
} from '@ant-design/icons';
import { IconFont } from '@/components/IconFont';

export default {
  log: <IconFont type='icon-log' />,
  systemLog: <IconFont type='icon-systemLog' />,
  utilBox: <IconFont type='icon-utilBox' />,
  pda: <IconFont type={'icon-PDA'} />,
  layout: <IconFont type='icon-layout' />,
  charger: <IconFont type='icon-charger2' />,
  taskManage: <IconFont type='icon-taskManage' />,
  report: <IconFont type='icon-report' />,
  storage: <IconFont type='icon-storage' />,
  equipment: <IconFont type='icon-automation' />,
  binding: <IconFont type='icon-binding' />,
  dependency: <IconFont type='icon-dependency' />,
  map: <IconFont type='icon-map' />,
  editor: <IconFont type='icon-mapEditor' />,
  monitor: <IconFont type='icon-mapMonitor' />,
  section: <IconFont type='icon-section' />,
  userRole: <IconFont type='icon-role' />,
  executing: <IconFont type='icon-executing' />,
  pod: <IconFont type='icon-pod' />,
  upgrade: <IconFont type='icon-upgrade' />,
  performanceMonitoring: <IconFont type='icon-performance' />,
  db: <IconFont type='icon-db' />,

  quickTask: <FireOutlined />,
  customTask: <FunctionOutlined />,
  trigger: <ThunderboltOutlined />,
  taskQueue: <ExceptionOutlined />,
  taskExecuted: <FileSearchOutlined />,
  mockTask: <ProjectOutlined />,
  scoringAlgorithm: <DeploymentUnitOutlined />,
  limit: <ControlOutlined />,
  api: <ApiOutlined />,
  list: <ProfileOutlined />,
  strategy: <ShareAltOutlined />,
  planning: <ScheduleOutlined />,
  history: <HistoryOutlined />,
  load: <CodepenOutlined />,
  translate: <TranslationOutlined />,
  environment: <EnvironmentOutlined />,
  lock: <LockOutlined />,
  vehicle: <CarOutlined />,
  user: <UserOutlined />,
  home: <HomeOutlined />,
  ie: <IeOutlined />,
  richEditor: <MediumOutlined />,
  screenReport: <FundProjectionScreenOutlined />,
  menu: <UnorderedListOutlined />,
  subscription: <PaperClipOutlined />,
  alert: <BellOutlined />,
  feedback: <MessageOutlined />,
};
