import React from 'react';
import {
  ApiOutlined,
  CarOutlined,
  CodepenOutlined,
  ControlOutlined,
  DeploymentUnitOutlined,
  EnvironmentOutlined,
  ExceptionOutlined,
  FileSearchOutlined,
  FundProjectionScreenOutlined,
  HistoryOutlined,
  HomeOutlined,
  IeOutlined,
  LockOutlined,
  MediumOutlined,
  NotificationOutlined,
  ProfileOutlined,
  ProjectOutlined,
  ScheduleOutlined,
  ShareAltOutlined,
  TranslationOutlined,
  UserOutlined,
} from '@ant-design/icons';
import { IconFont } from '@/components/IconFont';

export default {
  log: <IconFont type="icon-log" />,
  layout: <IconFont type="icon-layout" />,
  charger: <IconFont type="icon-charger2" />,
  taskManage: <IconFont type="icon-taskManage" />,
  report: <IconFont type="icon-report" />,
  customConfig: <IconFont type="icon-customConfig" />,
  authorize: <IconFont type="icon-authorize" />,
  storage: <IconFont type="icon-storage" />,
  equipment: <IconFont type="icon-automation" />,
  binding: <IconFont type="icon-binding" />,
  dependency: <IconFont type="icon-dependency" />,
  map: <IconFont type="icon-map" />,
  section: <IconFont type="icon-section" />,
  trigger: <IconFont type="icon-trigger" />,
  userRole: <IconFont type="icon-role" />,
  executing: <IconFont type="icon-executing" />,
  pod: <IconFont type="icon-huojiaxinxi" />,

  taskQueue: <ExceptionOutlined />,
  taskExecuted: <FileSearchOutlined />,
  mockTask: <ProjectOutlined />,
  scoringAlgorithm: <DeploymentUnitOutlined />,
  limit: <ControlOutlined />,
  api: <ApiOutlined />,
  list: <ProfileOutlined />,
  strategy: <ShareAltOutlined />,
  planning: <ScheduleOutlined />,
  history: <HistoryOutlined />,
  load: <CodepenOutlined />,
  translate: <TranslationOutlined />,
  environment: <EnvironmentOutlined />,
  lock: <LockOutlined />,
  vehicle: <CarOutlined />,
  user: <UserOutlined />,
  home: <HomeOutlined />,
  ie: <IeOutlined />,
  richEditor: <MediumOutlined />,
  notification: <NotificationOutlined />,
  screenReport: <FundProjectionScreenOutlined />,
};
