export const mockData = {
  code: 'ltp_VaPbVs5N',
  name: '1',
  row: 4,
  column: 2,
  height: 100,
  width: 120,
  depth: 90,
  laminateHeight: 10,
  id: null,
  podFaceList: [
    {
      name: 'A',
      angle: 0,
      bins: [
        [
          {
            code: 'AA01',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: 60,
            barycenterY: 45,
            barycenterZ: 50,
          },
          {
            code: 'AA02',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: -60,
            barycenterY: 45,
            barycenterZ: 50,
          },
        ],
        [
          {
            code: 'AB01',
            height: 200,
            width: 240,
            depth: 90,
            barycenterX: 0,
            barycenterY: 45,
            barycenterZ: 160,
          },
        ],
        [
          {
            code: 'AC01',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: 60,
            barycenterY: 45,
            barycenterZ: 270,
          },
          {
            code: 'AC02',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: -60,
            barycenterY: 45,
            barycenterZ: 270,
          },
        ],
      ],
    },
    {
      name: 'C',
      angle: 180,
      bins: [
        [
          {
            code: 'CA01',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: 60,
            barycenterY: -45,
            barycenterZ: 50,
          },
          {
            code: 'CA02',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: -60,
            barycenterY: -45,
            barycenterZ: 50,
          },
        ],
        [
          {
            code: 'CB01',
            height: 200,
            width: 240,
            depth: 90,
            barycenterX: 0,
            barycenterY: -45,
            barycenterZ: 160,
          },
        ],
        [
          {
            code: 'CC01',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: 60,
            barycenterY: -45,
            barycenterZ: 270,
          },
          {
            code: 'CC02',
            height: 100,
            width: 120,
            depth: 90,
            barycenterX: -60,
            barycenterY: -45,
            barycenterZ: 270,
          },
        ],
      ],
    },
  ],
};
