export const storage = {
  name: '储位类型名称',
  code: '储位编码',
  row: 3,
  column: 4,
  laminateHeight: 2,
  podFaceList: [
    {
      name: 'A',
      angle: 0,
      bins: [
        [
          {
            code: 'AA01',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'AA02',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'AA03',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
        ],
        [
          {
            code: 'AB01',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'AB02',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
        ],
      ],
    },
    {
      name: 'B',
      angle: 0,
      bins: [
        [
          {
            code: 'BA01',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'BA02',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'BA03',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
        ],
        [
          {
            code: 'BB01',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
          {
            code: 'BB02',
            height: 12,
            width: 20,
            depth: 10,
            barycenterX: 12,
            barycenterY: 12,
            barycenterZ: 12,
          },
        ],
      ],
    },
  ],
};
