export const MockMapDataMulti = {
  id: '627b9b3acec59534a8c0db8c',
  name: 'cs',
  desc: null,
  sectionId: 6,
  autoGenCellIdStart: 1,
  activeFlag: true,
  cellMap: {
    1: {
      id: 1,
      naviId: '1',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 0,
      y: 0,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    2: {
      id: 2,
      naviId: '2',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 1225,
      y: 0,
      nx: 1225,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    3: {
      id: 3,
      naviId: '3',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 2450,
      y: 0,
      nx: 2450,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    4: {
      id: 4,
      naviId: '4',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 3675,
      y: 0,
      nx: 3675,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    5: {
      id: 5,
      naviId: '5',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 4900,
      y: 0,
      nx: 4900,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    6: {
      id: 6,
      naviId: '6',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 6125,
      y: 0,
      nx: 6125,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    7: {
      id: 7,
      naviId: '7',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 0,
      y: -1000,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    8: {
      id: 8,
      naviId: '8',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 1225,
      y: -1000,
      nx: 1225,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    9: {
      id: 9,
      naviId: '9',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 2450,
      y: -1000,
      nx: 2450,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    10: {
      id: 10,
      naviId: 'LM1',
      navigationType: 'seerslam',
      type: 'Normal',
      x: 0,
      y: 0,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
  },
  connectCellMap: null,
  logicAreaList: [
    {
      id: 0,
      name: 'DEFAULT',
      routeMap: {
        DEFAULT: {
          name: 'DEFAULT',
          code: 'DEFAULT',
          desc: null,
          waitCellIds: null,
          followCellIds: null,
          blockCellIds: null,
          nonStopCellIds: null,
          relations: [
            {
              source: 2,
              target: 3,
              type: 'StraightPath',
              angle: 90,
              cost: 10,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 8,
              target: 9,
              type: 'StraightPath',
              angle: 90,
              cost: 10,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 3,
              target: 2,
              type: 'StraightPath',
              angle: 270,
              cost: 20,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 9,
              target: 8,
              type: 'StraightPath',
              angle: 270,
              cost: 20,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 8,
              target: 2,
              type: 'StraightPath',
              angle: 0,
              cost: 100,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 9,
              target: 3,
              type: 'StraightPath',
              angle: 0,
              cost: 100,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 2,
              target: 8,
              type: 'StraightPath',
              angle: 180,
              cost: 1000,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 3,
              target: 9,
              type: 'StraightPath',
              angle: 180,
              cost: 1000,
              distance: 1000,
              control1: null,
              control2: null,
            },
          ],
          rotateAreaMap: null,
          relationMap: null,
          tunnels: null,
          cellCostMap: null,
          turnCellId: null,
          storeCellDTOList: null,
        },
      },
      obstacles: [],
      restCells: [],
      storeCellIds: [],
      taskCellIds: null,
      rotateCellIds: null,
      safeAreaCellIds: null,
      workstationList: [],
      dumpStations: [],
      chargerList: [],
      commonList: [],
      intersectionList: null,
      emergencyStopFixedList: null,
      backGround: null,
      zoneMarker: [
        {
          code: 'RECT_ECGZcF',
          x: 3284,
          y: -201,
          width: 1916,
          height: 627,
          color: '#1890ff',
          type: 'RECT',
          text: '123',
        },
      ],
      labels: null,
    },
  ],
  elevatorList: null,
  transform: {},
  intMapCell: null,
  elevatorInnerCells: null,
  innerCellMap: null,
  assistRotateCellIds: null,
  deepStoreCellMap: null,
  targetCellRelationMap: null,
  localUpdateTime: '2022-05-11T19:47:45.209',
  naviCellMap: null,
  createdByUser: null,
  createTime: '2022-05-11 19:17:14',
  updatedByUser: null,
  updateTime: '2022-05-11 19:17:14',
  ever: '1.0.0',
  mver: '1.0.0',
};

export const MockMapWithProgram = {
  id: '627b9b3acec59534a8c0db8c',
  name: 'cs',
  desc: null,
  sectionId: 6,
  autoGenCellIdStart: 1,
  activeFlag: true,
  cellMap: {
    1: {
      id: 1,
      naviId: '1',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 0,
      y: 0,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    2: {
      id: 2,
      naviId: '2',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 1225,
      y: 0,
      nx: 1225,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    3: {
      id: 3,
      naviId: '3',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 2450,
      y: 0,
      nx: 2450,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    4: {
      id: 4,
      naviId: '4',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 3675,
      y: 0,
      nx: 3675,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    5: {
      id: 5,
      naviId: '5',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 4900,
      y: 0,
      nx: 4900,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    6: {
      id: 6,
      naviId: '6',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 6125,
      y: 0,
      nx: 6125,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    7: {
      id: 7,
      naviId: '7',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 0,
      y: -1000,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    8: {
      id: 8,
      naviId: '8',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 1225,
      y: -1000,
      nx: 1225,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    9: {
      id: 9,
      naviId: '9',
      navigationType: 'mqrcode',
      type: 'Normal',
      x: 2450,
      y: -1000,
      nx: 2450,
      ny: 0,
      logicId: 0,
      additional: {},
    },
    10: {
      id: 10,
      naviId: 'LM1',
      navigationType: 'seerslam',
      type: 'Normal',
      x: 0,
      y: 0,
      nx: 0,
      ny: 0,
      logicId: 0,
      additional: {},
    },
  },
  connectCellMap: null,
  logicAreaList: [
    {
      id: 0,
      name: 'DEFAULT',
      routeMap: {
        DEFAULT: {
          name: 'DEFAULT',
          code: 'DEFAULT',
          desc: null,
          waitCellIds: null,
          followCellIds: null,
          blockCellIds: null,
          nonStopCellIds: null,
          relations: [
            {
              source: 2,
              target: 3,
              type: 'StraightPath',
              angle: 90,
              cost: 10,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 8,
              target: 9,
              type: 'StraightPath',
              angle: 90,
              cost: 10,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 3,
              target: 2,
              type: 'StraightPath',
              angle: 270,
              cost: 20,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 9,
              target: 8,
              type: 'StraightPath',
              angle: 270,
              cost: 20,
              distance: 1225,
              control1: null,
              control2: null,
            },
            {
              source: 8,
              target: 2,
              type: 'StraightPath',
              angle: 0,
              cost: 100,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 9,
              target: 3,
              type: 'StraightPath',
              angle: 0,
              cost: 100,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 2,
              target: 8,
              type: 'StraightPath',
              angle: 180,
              cost: 1000,
              distance: 1000,
              control1: null,
              control2: null,
            },
            {
              source: 3,
              target: 9,
              type: 'StraightPath',
              angle: 180,
              cost: 1000,
              distance: 1000,
              control1: null,
              control2: null,
            },
          ],
          rotateAreaMap: null,
          relationMap: null,
          tunnels: null,
          cellCostMap: null,
          turnCellId: null,
          storeCellDTOList: null,
          programing: {
            cells: {},
            relations: {
              '9-8': [
                {
                  actionType: 'SYSTEM_ACTION_CustomTaskAction',
                  actionId: 'SYSTEM_ACTION_CustomTaskAction',
                  actionDescription: '触发自定义任务',
                  sequenceId: null,
                  levels: null,
                  blockingType: 'NONE',
                  released: false,
                  actionState: null,
                  adapterType: 'SYSTEM',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: 'BEGIN',
                  actionParameters: [
                    {
                      key: null,
                      value: '1',
                      valueDataType: 'INTEGER',
                      description: '小车Id',
                      isOptional: null,
                      name: '小车Id',
                      code: 'Vehicle',
                    },
                    {
                      key: null,
                      value: '1',
                      valueDataType: 'INTEGER',
                      description: '目标点Cell',
                      isOptional: null,
                      name: '目标点Cell',
                      code: 'CELL',
                    },
                    {
                      key: null,
                      value: '1',
                      valueDataType: 'STRING',
                      description: '路线区',
                      isOptional: null,
                      name: '路线区',
                      code: 'SCOPE',
                    },
                    {
                      key: null,
                      value: '1',
                      valueDataType: 'STRING',
                      description: '任务类型',
                      isOptional: null,
                      name: '任务类型',
                      code: 'TASK',
                    },
                  ],
                  targetId: null,
                  targetMethodType: null,
                },
                {
                  actionType: 'SYSTEM_ACTION_CustomTaskAction',
                  actionId: 'SYSTEM_ACTION_CustomTaskAction',
                  actionDescription: '触发自定义任务',
                  sequenceId: null,
                  levels: null,
                  blockingType: 'NONE',
                  released: false,
                  actionState: null,
                  adapterType: 'SYSTEM',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: 'ONROAD',
                  actionParameters: [
                    {
                      key: null,
                      value: '2',
                      valueDataType: 'INTEGER',
                      description: '小车Id',
                      isOptional: null,
                      name: '小车Id',
                      code: 'Vehicle',
                    },
                    {
                      key: null,
                      value: '2',
                      valueDataType: 'INTEGER',
                      description: '目标点Cell',
                      isOptional: null,
                      name: '目标点Cell',
                      code: 'CELL',
                    },
                    {
                      key: null,
                      value: '2',
                      valueDataType: 'STRING',
                      description: '路线区',
                      isOptional: null,
                      name: '路线区',
                      code: 'SCOPE',
                    },
                    {
                      key: null,
                      value: '2',
                      valueDataType: 'STRING',
                      description: '任务类型',
                      isOptional: null,
                      name: '任务类型',
                      code: 'TASK',
                    },
                  ],
                  targetId: null,
                  targetMethodType: null,
                },
                {
                  actionType: 'SYSTEM_ACTION_CustomTaskAction',
                  actionId: 'SYSTEM_ACTION_CustomTaskAction',
                  actionDescription: '触发自定义任务',
                  sequenceId: null,
                  levels: null,
                  blockingType: 'NONE',
                  released: false,
                  actionState: null,
                  adapterType: 'SYSTEM',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: 'END',
                  actionParameters: [
                    {
                      key: null,
                      value: '3',
                      valueDataType: 'INTEGER',
                      description: '小车Id',
                      isOptional: null,
                      name: '小车Id',
                      code: 'Vehicle',
                    },
                    {
                      key: null,
                      value: '3',
                      valueDataType: 'INTEGER',
                      description: '目标点Cell',
                      isOptional: null,
                      name: '目标点Cell',
                      code: 'CELL',
                    },
                    {
                      key: null,
                      value: '3',
                      valueDataType: 'STRING',
                      description: '路线区',
                      isOptional: null,
                      name: '路线区',
                      code: 'SCOPE',
                    },
                    {
                      key: null,
                      value: '3',
                      valueDataType: 'STRING',
                      description: '任务类型',
                      isOptional: null,
                      name: '任务类型',
                      code: 'TASK',
                    },
                  ],
                  targetId: null,
                  targetMethodType: null,
                },
              ],
            },
            zones: {},
          },
        },
      },
      obstacles: [],
      restCells: [],
      storeCellIds: [],
      taskCellIds: null,
      rotateCellIds: null,
      safeAreaCellIds: null,
      workstationList: [],
      dumpStations: [],
      chargerList: [],
      commonList: [],
      intersectionList: null,
      emergencyStopFixedList: null,
      backGround: null,
      zoneMarker: [
        {
          code: 'RECT_ECGZcF',
          x: 3284,
          y: -201,
          width: 1916,
          height: 627,
          color: '#1890ff',
          type: 'RECT',
          text: '123',
        },
      ],
      labels: null,
    },
  ],
  elevatorList: null,
  transform: {},
  intMapCell: null,
  elevatorInnerCells: null,
  innerCellMap: null,
  assistRotateCellIds: null,
  deepStoreCellMap: null,
  targetCellRelationMap: null,
  localUpdateTime: '2022-05-11T19:47:45.209',
  naviCellMap: null,
  createdByUser: null,
  createTime: '2022-05-11 19:17:14',
  updatedByUser: null,
  updateTime: '2022-05-11 19:17:14',
  ever: '1.0.0',
  mver: '1.0.0',
};

export const AllAdapters = {
  MUSHINY_SORTER_ADAPTER: {
    adapterType: {
      id: 'MUSHINY_SORTER_ADAPTER',
      code: 'MUSHINY_SORTER_ADAPTER',
      name: '分拣',
      description: null,
      vehicleConnectType: '',
      vehicleTypes: [
        {
          id: null,
          code: 'sorter',
          sectionId: null,
          isReadOnly: true,
          isUserVisible: true,
          name: '分拣',
          fixTureModel: null,
          vehicleModel: {
            code: 'sorter',
            name: '分拣模型',
            icon: null,
            geoModel: {
              dimension: { front: 455, rear: 455, left: 370, right: 370, radius: 480, height: 0 },
              position: { x: 0, y: 0, z: 0 },
              angle: 0.0,
            },
          },
          actionTemplate: {
            id: null,
            code: 'sorter',
            name: '分拣动作模型',
            actionModels: {
              Go: {
                id: null,
                actionCode: 'A',
                actionName: '行驶',
                vehicleAction: {
                  params: null,
                  priority: 0,
                  indActionCmdAndMsg: null,
                  indActionFinishCmd: 0,
                  actionList: ['DISTANCE', 'SPEED'],
                  actionParams: null,
                  blockingType: 'NONE',
                  simulatorIndex: null,
                  simulatorSpeed: null,
                  vehicleActionMsg: null,
                  indAction: false,
                  slowAction: false,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
              },
              Turn: {
                id: null,
                actionCode: 'B',
                actionName: '转弯',
                vehicleAction: {
                  params: null,
                  priority: 0,
                  indActionCmdAndMsg: null,
                  indActionFinishCmd: 0,
                  actionList: ['ANGLE'],
                  actionParams: null,
                  blockingType: 'SOFT',
                  simulatorIndex: null,
                  simulatorSpeed: null,
                  vehicleActionMsg: null,
                  indAction: false,
                  slowAction: false,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
              },
              Finish: {
                id: null,
                actionCode: 'H2',
                actionName: '完成',
                vehicleAction: {
                  params: null,
                  priority: 0,
                  indActionCmdAndMsg: null,
                  indActionFinishCmd: 0,
                  actionList: [],
                  actionParams: null,
                  blockingType: 'SOFT',
                  simulatorIndex: null,
                  simulatorSpeed: null,
                  vehicleActionMsg: null,
                  indAction: false,
                  slowAction: false,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
              },
            },
          },
          navigationType: 'cell',
          vehicleAdapter: 'MUSHINY_SORTER_ADAPTER',
          lockStrategy: null,
          supportScene: ['EMPTY_RUN', 'CHARGE_RUN', 'REST_RUN'],
        },
      ],
      taskHandlerClass: null,
      otherInfo: null,
    },
    adapterModel: null,
  },
};

// VEHICLE, SYSTEM, EQUIPMENT
export const ProgramingConfigurationList = {
  SYSTEM: [
    {
      actionType: 'SYSTEM_ACTION_CustomTaskAction',
      actionId: 'SYSTEM_ACTION_CustomTaskAction',
      actionDescription: '触发自定义任务',
      sequenceId: null,
      levels: null,
      blockingType: 'NONE',
      released: false,
      actionState: null,
      adapterType: 'SYSTEM',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: null,
      actionParameters: [
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '小车Id',
          isOptional: null,
          name: '小车Id',
          code: 'Vehicle',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '目标点Cell',
          isOptional: null,
          name: '目标点Cell',
          code: 'CELL',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '路线区',
          isOptional: null,
          name: '路线区',
          code: 'SCOPE',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '任务类型',
          isOptional: null,
          name: '任务类型',
          code: 'TASK',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'SYSTEM_ACTION_NotifyAction',
      actionId: 'SYSTEM_ACTION_NotifyAction',
      actionDescription: '到点位上报一个事件',
      sequenceId: null,
      levels: null,
      blockingType: 'NONE',
      released: false,
      actionState: null,
      adapterType: 'SYSTEM',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: null,
      actionParameters: [
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '小车id',
          isOptional: null,
          name: '小车id',
          code: 'Vehicle',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '任务id',
          isOptional: null,
          name: '任务id',
          code: 'TASK',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '任务步骤',
          isOptional: null,
          name: '任务步骤',
          code: 'STEP',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '货架id',
          isOptional: null,
          name: '货架id',
          code: 'POD',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '通知事件发生时的货架方向',
          isOptional: null,
          name: '货架方向',
          code: 'ANGLE',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '通知事件发生时的点位',
          isOptional: null,
          name: '点位',
          code: 'CELL',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
  ],
  DEVICE: [
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_FIRST_OPEN',
      actionDescription: '开1号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_SECOND_OPEN',
      actionDescription: '开2号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_THIRD_OPEN',
      actionDescription: '开3号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_CLOSE',
      actionDescription: '关灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
  ],
};

export const VehicleModelData = [
  {
    code: 'vehicleType1',
    ids: [1, 2, 3, 4],
    types: ['loadTypeA', 'loadTypeB', 'loadTypeC', 'loadTypeD'],
  },
  {
    code: 'vehicleType2',
    ids: [5, 6, 7, 8],
    types: ['loadTypeB'],
  },
];

export const VehicleGroupModelData = [
  {
    code: 'group1',
    ids: [1, 2, 3, 4],
    types: ['loadA', 'loadB'],
  },
  {
    code: 'group2',
    ids: [5, 6, 7, 8],
    types: ['loadC', 'loadD'],
  },
];

export const LoadModelData = [
  {
    code: 'loadTypeA',
    ids: ['loadTypeA1', 'loadTypeA2', 'loadTypeA3'],
  },
  {
    code: 'loadTypeB',
    ids: ['loadTypeB1', 'loadTypeB2', 'loadTypeB3'],
  },
  {
    code: 'loadTypeC',
    ids: ['loadTypeC1', 'loadTypeC2', 'loadTypeC3'],
  },
  {
    code: 'loadTypeD',
    ids: ['loadTypeD1', 'loadTypeD2', 'loadTypeD3'],
  },
];

export const LoadGroupModelData = [
  {
    code: 'loadGroup1',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeB', 'loadTypeD'],
  },
  {
    code: 'loadGroup2',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeB'],
  },
  {
    code: 'loadGroup3',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeE'],
  },
  {
    code: 'loadGroup4',
    ids: ['loadIds'],
    types: ['loadTypeB', 'loadTypeE'],
  },
];

export const VehicleList = [
  {
    sectionId: 1,
    vehicleId: '1',
    vehicleType: 'latent',
    uniqueId: 'T_MUSHINY_LATENT_ADAPTER_A_1',
    vehicle: {
      id: 'T_MUSHINY_LATENT_ADAPTER_A_1',
      disabled: false,
      manualMode: false,
      maintain: false,
      register: true,
      statusFlag: null,
      isSimulator: true,
      brand: null,
      isLatent: true,
      lastTime: null,
      timeStamp: 0,
      others: null,
      sectionId: 1,
      adapterType: 'MUSHINY_LATENT_ADAPTER',
      vehicleId: '1',
      clusterIndex: null,
      token: null,
      vehicleType: 'latent',
      msgId: null,
    },
    vehicleInfo: {
      id: 'T_MUSHINY_LATENT_ADAPTER_A_1',
      logicId: 0,
      isEmpty: true,
      currentCellId: null,
      currentNaviId: 'null',
      x: null,
      y: null,
      battery: 80,
      batteryVoltage: 40,
      batteryTemperature: 40,
      direction: null,
      loads: null,
      loadAngle: null,
      speed: 0,
      level: null,
      isShowPod: true,
      timeStamp: 1654056368265,
      arriveTime: 1654056362750,
      sectionId: 1,
      adapterType: 'MUSHINY_LATENT_ADAPTER',
      vehicleId: '1',
      clusterIndex: null,
      token: null,
      vehicleType: 'latent',
      msgId: null,
    },
    vehicleWorkStatusDTO: {
      id: 'T_MUSHINY_LATENT_ADAPTER_A_1',
      sectionId: 1,
      vehicleStatus: 'Idle',
      errorStatus: null,
      onlineStatus: 'ONLINE',
      vehicleId: '1',
      timeStamp: 1654056362751,
      disabled: false,
      manualMode: false,
      vehicleType: 'latent',
      vehicleAdapter: 'MUSHINY_LATENT_ADAPTER',
      vehicleWaitTask: null,
      alertItemLevel: null,
      lastFullChargeTime: null,
      chargeTimesSinceLastFullCharge: 0,
    },
  },
];
