import { getRandomString } from '@/utils/util';
import { VehicleUpgradeState } from '@/packages/ResourceManage/Vehicle/upgradeConst';

export const ProgramingConfigurationList = {
  SYSTEM: [
    {
      actionType: 'SYSTEM_ACTION_CustomTaskAction',
      actionId: 'SYSTEM_ACTION_CustomTaskAction',
      actionDescription: '触发自定义任务',
      sequenceId: null,
      levels: null,
      blockingType: 'NONE',
      released: false,
      actionState: null,
      adapterType: 'SYSTEM',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: null,
      actionParameters: [
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '小车Id',
          isOptional: null,
          name: '小车Id',
          code: 'Vehicle',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '目标点Cell',
          isOptional: null,
          name: '目标点Cell',
          code: 'CELL',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '路线区',
          isOptional: null,
          name: '路线区',
          code: 'SCOPE',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '任务类型',
          isOptional: null,
          name: '任务类型',
          code: 'TASK',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'SYSTEM_ACTION_NotifyAction',
      actionId: 'SYSTEM_ACTION_NotifyAction',
      actionDescription: '到点位上报一个事件',
      sequenceId: null,
      levels: null,
      blockingType: 'NONE',
      released: false,
      actionState: null,
      adapterType: 'SYSTEM',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: null,
      actionParameters: [
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '小车id',
          isOptional: null,
          name: '小车id',
          code: 'Vehicle',
        },
        {
          key: null,
          value: null,
          valueDataType: 'STRING',
          description: '任务id',
          isOptional: null,
          name: '任务id',
          code: 'TASK',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '任务步骤',
          isOptional: null,
          name: '任务步骤',
          code: 'STEP',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '货架id',
          isOptional: null,
          name: '货架id',
          code: 'POD',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '通知事件发生时的货架方向',
          isOptional: null,
          name: '货架方向',
          code: 'ANGLE',
        },
        {
          key: null,
          value: null,
          valueDataType: 'INTEGER',
          description: '通知事件发生时的点位',
          isOptional: null,
          name: '点位',
          code: 'CELL',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
  ],
  DEVICE: [
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_FIRST_OPEN',
      actionDescription: '开1号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_SECOND_OPEN',
      actionDescription: '开2号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_THIRD_OPEN',
      actionDescription: '开3号灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'true',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
    {
      actionType: 'DEVICE_TYPE_LampModbusTCPDeviceType',
      actionId: 'MODBUS_CLOSE',
      actionDescription: '关灯动作',
      sequenceId: null,
      levels: null,
      blockingType: 'HARD',
      released: false,
      actionState: null,
      adapterType: 'DEVICE',
      isReadOnly: false,
      isUserVisible: true,
      deviceId: '5',
      actionParameters: [
        {
          key: null,
          value: '16',
          valueDataType: 'STRING',
          description: '配置开1号灯寄存器地址',
          isOptional: null,
          name: '1号灯寄存器地址',
          code: 'first_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开1号灯对应slaveId',
          isOptional: null,
          name: '1号灯设备地址',
          code: 'first_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开1号灯对应开关值',
          isOptional: null,
          name: '1号灯开关值',
          code: 'first_value',
        },
        {
          key: null,
          value: '17',
          valueDataType: 'STRING',
          description: '配置开2号灯对应地址',
          isOptional: null,
          name: '2号灯寄存器地址',
          code: 'second_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开2号灯对应slaveId',
          isOptional: null,
          name: '2号灯设备地址',
          code: 'second_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开2号灯对应开关值',
          isOptional: null,
          name: '2号灯开关值',
          code: 'second_value',
        },
        {
          key: null,
          value: '18',
          valueDataType: 'STRING',
          description: '配置开3号灯对应地址',
          isOptional: null,
          name: '3号灯寄存器地址',
          code: 'third_address',
        },
        {
          key: null,
          value: '1',
          valueDataType: 'STRING',
          description: '配置开3号灯对应slaveId',
          isOptional: null,
          name: '3号灯设备地址',
          code: 'third_slaveId',
        },
        {
          key: null,
          value: 'false',
          valueDataType: 'BOOL',
          description: '配置开3号灯对应开关值',
          isOptional: null,
          name: '3号灯开关值',
          code: 'third_value',
        },
      ],
      targetId: null,
      targetMethodType: null,
    },
  ],
};

export const VehicleModelData = [
  {
    code: 'vehicleType1',
    ids: [1, 2, 3, 4],
    types: ['loadTypeA', 'loadTypeB', 'loadTypeC', 'loadTypeD'],
  },
  {
    code: 'vehicleType2',
    ids: [5, 6, 7, 8],
    types: ['loadTypeB'],
  },
];

export const VehicleGroupModelData = [
  {
    code: 'group1',
    ids: [1, 2, 3, 4],
    types: ['loadA', 'loadB'],
  },
  {
    code: 'group2',
    ids: [5, 6, 7, 8],
    types: ['loadC', 'loadD'],
  },
];

export const LoadModelData = [
  {
    code: 'loadTypeA',
    ids: ['loadTypeA1', 'loadTypeA2', 'loadTypeA3'],
  },
  {
    code: 'loadTypeB',
    ids: ['loadTypeB1', 'loadTypeB2', 'loadTypeB3'],
  },
  {
    code: 'loadTypeC',
    ids: ['loadTypeC1', 'loadTypeC2', 'loadTypeC3'],
  },
  {
    code: 'loadTypeD',
    ids: ['loadTypeD1', 'loadTypeD2', 'loadTypeD3'],
  },
];

export const LoadGroupModelData = [
  {
    code: 'loadGroup1',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeB', 'loadTypeD'],
  },
  {
    code: 'loadGroup2',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeB'],
  },
  {
    code: 'loadGroup3',
    ids: ['loadIds'],
    types: ['loadTypeA', 'loadTypeE'],
  },
  {
    code: 'loadGroup4',
    ids: ['loadIds'],
    types: ['loadTypeB', 'loadTypeE'],
  },
];

export const AllAdapters = {
  MUSHINY_LATENT_ADAPTER: {
    adapterType: {
      id: 'MUSHINY_LATENT_ADAPTER',
      code: 'MUSHINY_LATENT_ADAPTER',
      name: '牧星潜伏车',
      description: null,
      vehicleConnectType: '',
      vehicleTypes: [
        {
          id: null,
          code: 'latent',
          sectionId: null,
          isReadOnly: true,
          isUserVisible: true,
          name: '潜伏类型',
          fixTureModel: null,
          vehicleModel: {
            code: 'latent',
            name: '潜伏车模型',
            icon: null,
            geoModel: {
              dimension: { front: 470, rear: 470, right: 355, left: 355, radius: 500, height: 0 },
              position: { x: 0, y: 0, z: 0 },
              angle: 0.0,
            },
          },
          actionTemplate: {
            id: null,
            code: 'latent',
            name: '潜伏动作模型',
            actionModels: {
              B: {
                id: null,
                actionCode: 'B',
                actionName: '转弯',
                vehicleAction: {
                  actionType: 'Turn',
                  actionId: 'B',
                  actionDescription: 'turning to walk',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'GOTO_ROTATING',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'ANGLE',
                      value: 'ANGLE',
                      valueDataType: 'STRING',
                      description: 'ANGLE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '角度',
                      code: 'ANGLE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 1,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              D10: {
                id: null,
                actionCode: 'D10',
                actionName: '盲顶',
                vehicleAction: {
                  actionType: 'Fetch',
                  actionId: 'D10',
                  actionDescription: 'BlindFetch',
                  sequenceId: null,
                  levels: ['BODY', 'FROCK'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                    FROCK: {
                      uniqueId: null,
                      type: 'LOAD',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'LOAD',
                      value: 'LOAD',
                      valueDataType: 'STRING',
                      description: 'LOAD',
                      isOptional: false,
                      isReadOnly: true,
                      name: '载具',
                      code: 'LOAD',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 9,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              C: {
                id: null,
                actionCode: 'C',
                actionName: '载具旋转',
                vehicleAction: {
                  actionType: 'ToteTurn',
                  actionId: 'C',
                  actionDescription: 'toteTurn',
                  sequenceId: null,
                  levels: ['BODY', 'FROCK'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                    FROCK: {
                      uniqueId: null,
                      type: 'LOAD',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'GOTO_ROTATING',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'ANGLE',
                      value: 'ANGLE',
                      valueDataType: 'STRING',
                      description: 'ANGLE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '角度',
                      code: 'ANGLE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 3,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              D11: {
                id: null,
                actionCode: 'D11',
                actionName: '盲降',
                vehicleAction: {
                  actionType: 'BlindPut',
                  actionId: 'D11',
                  actionDescription: 'BlindPut',
                  sequenceId: null,
                  levels: ['BODY', 'FROCK'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                    FROCK: {
                      uniqueId: null,
                      type: 'LOAD',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: null,
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 2,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              I0: {
                id: null,
                actionCode: 'I0',
                actionName: '开始充电',
                vehicleAction: {
                  actionType: 'Charge',
                  actionId: 'I0',
                  actionDescription: 'start to charge',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'HARD',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 0,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              H1: {
                id: null,
                actionCode: 'H1',
                actionName: '暂停',
                vehicleAction: {
                  actionType: 'Pause',
                  actionId: 'H1',
                  actionDescription: 'pause path',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'HARD',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 0,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              I2: {
                id: null,
                actionCode: 'I2',
                actionName: '结束充电',
                vehicleAction: {
                  actionType: 'StopCharge',
                  actionId: 'I2',
                  actionDescription: 'stop charging',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'HARD',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 0,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              F0: {
                id: null,
                actionCode: 'F0',
                actionName: '纠偏直行后退',
                vehicleAction: {
                  actionType: 'Go',
                  actionId: 'F0',
                  actionDescription: 'walk in a straight line',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'NONE',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'DISTANCE',
                      value: 'DISTANCE',
                      valueDataType: 'STRING',
                      description: 'DISTANCE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '距离',
                      code: 'DISTANCE',
                    },
                    {
                      uniqueId: null,
                      key: 'SPEED',
                      value: 'SPEED',
                      valueDataType: 'STRING',
                      description: 'SPEED',
                      isOptional: false,
                      isReadOnly: true,
                      name: '速度',
                      code: 'DISTANCE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 4,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              H2: {
                id: null,
                actionCode: 'H2',
                actionName: '完成',
                vehicleAction: {
                  actionType: 'Finish',
                  actionId: 'H2',
                  actionDescription: 'finish path',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'HARD',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 0,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              D0: {
                id: null,
                actionCode: 'D0',
                actionName: '顶升',
                vehicleAction: {
                  actionType: 'Fetch',
                  actionId: 'D0',
                  actionDescription: 'Fetch',
                  sequenceId: null,
                  levels: ['BODY', 'FROCK'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                    FROCK: {
                      uniqueId: null,
                      type: 'LOAD',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'LOAD',
                      value: 'LOAD',
                      valueDataType: 'STRING',
                      description: 'LOAD',
                      isOptional: false,
                      isReadOnly: true,
                      name: '载具',
                      code: 'LOAD',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 9,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              D1: {
                id: null,
                actionCode: 'D1',
                actionName: '下降',
                vehicleAction: {
                  actionType: 'Put',
                  actionId: 'D1',
                  actionDescription: 'Put',
                  sequenceId: null,
                  levels: ['BODY', 'FROCK'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                    FROCK: {
                      uniqueId: null,
                      type: 'LOAD',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: null,
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 2,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              A0: {
                id: null,
                actionCode: 'A0',
                actionName: '纠偏直行前进',
                vehicleAction: {
                  actionType: 'Go',
                  actionId: 'A0',
                  actionDescription: 'walk in a straight line',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'NONE',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'DISTANCE',
                      value: 'DISTANCE',
                      valueDataType: 'STRING',
                      description: 'DISTANCE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '距离',
                      code: 'DISTANCE',
                    },
                    {
                      uniqueId: null,
                      key: 'SPEED',
                      value: 'SPEED',
                      valueDataType: 'STRING',
                      description: 'SPEED',
                      isOptional: false,
                      isReadOnly: true,
                      name: '速度',
                      code: 'DISTANCE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 4,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              B1: {
                id: null,
                actionCode: 'B1',
                actionName: '非同步转弯',
                vehicleAction: {
                  actionType: 'Turn',
                  actionId: 'B1',
                  actionDescription: 'sync turning to walk',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'GOTO_ROTATING',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'ANGLE',
                      value: 'ANGLE',
                      valueDataType: 'STRING',
                      description: 'ANGLE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '角度',
                      code: 'ANGLE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 1,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              A1: {
                id: null,
                actionCode: 'A1',
                actionName: '纠偏直行后退',
                vehicleAction: {
                  actionType: 'Go',
                  actionId: 'A1',
                  actionDescription: 'back in a straight line',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'Rectangle',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'NONE',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'DISTANCE',
                      value: 'DISTANCE',
                      valueDataType: 'STRING',
                      description: 'DISTANCE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '距离',
                      code: 'DISTANCE',
                    },
                    {
                      uniqueId: null,
                      key: 'SPEED',
                      value: 'SPEED',
                      valueDataType: 'STRING',
                      description: 'SPEED',
                      isOptional: false,
                      isReadOnly: true,
                      name: '速度',
                      code: 'DISTANCE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 4,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              B2: {
                id: null,
                actionCode: 'B2',
                actionName: '同步转弯',
                vehicleAction: {
                  actionType: 'Turn',
                  actionId: 'B2',
                  actionDescription: 'same turn to walk',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'GOTO_ROTATING',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'ANGLE',
                      value: 'ANGLE',
                      valueDataType: 'STRING',
                      description: 'ANGLE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '角度',
                      code: 'ANGLE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 1,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
              B3: {
                id: null,
                actionCode: 'B3',
                actionName: '盲非同步转',
                vehicleAction: {
                  actionType: 'Turn',
                  actionId: 'B3',
                  actionDescription: 'No Sync turning to walk',
                  sequenceId: null,
                  levels: ['BODY'],
                  levelAngle: {
                    BODY: {
                      uniqueId: null,
                      type: 'VEHICLE',
                      angle: null,
                      dimension: null,
                      targetAngle: null,
                      arriveBoxType: 'GOTO_ROTATING',
                    },
                  },
                  lockLevelMap: null,
                  blockingType: 'SOFT',
                  released: false,
                  releaseTime: 0,
                  actionState: null,
                  adapterType: 'VEHICLE',
                  isReadOnly: false,
                  isUserVisible: true,
                  deviceId: null,
                  timing: null,
                  actionParameters: [
                    {
                      uniqueId: null,
                      key: 'ANGLE',
                      value: 'ANGLE',
                      valueDataType: 'STRING',
                      description: 'ANGLE',
                      isOptional: false,
                      isReadOnly: true,
                      name: '角度',
                      code: 'ANGLE',
                    },
                  ],
                  otherInfo: null,
                  vehicleType: null,
                  operateType: null,
                  finishTime: 0,
                  priority: 1,
                  targetId: null,
                  targetMethodType: null,
                },
                vehicleActionRelation: null,
                mutualExclusiveActionType: null,
                speed: null,
              },
            },
            coefficient: null,
          },
          navigationType: 'mqrcode',
          vehicleAdapter: 'MUSHINY_LATENT_ADAPTER',
          lockStrategy: null,
          containerType: {
            code: 'latent',
            size: 1,
            width: null,
            length: null,
            canPileUp: false,
            supportLoadType: ['LOAD_TYPE_LatentJackingLoadType'],
          },
          supportScene: ['EMPTY_RUN', 'CHARGE_RUN', 'RUN_TO_REST'],
        },
      ],
      taskHandlerClass: null,
      otherInfo: { port: '8899', version: '3.0.0' },
      supportActions: null,
    },
    adapterModel: null,
  },
};

export const VehicleList = [
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_15',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '15',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_14',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '14',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_13',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '13',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_12',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '12',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_11',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '11',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
  {
    id: 'T_MUSHINY_LATENT_ADAPTER_A_10',
    disabled: false,
    manualMode: false,
    maintain: false,
    register: true,
    statusFlag: null,
    isSimulator: true,
    brand: null,
    isLatent: false,
    lastTime: null,
    timeStamp: 0,
    others: null,
    sectionId: 3,
    adapterType: 'MUSHINY_LATENT_ADAPTER',
    vehicleId: '10',
    clusterIndex: null,
    token: null,
    vehicleType: 'latent',
    msgId: null,
  },
];

// 固件升级
export const UpgradeOrderDatasource = [
  {
    id: getRandomString(15),
    vehicles: [
      {
        uniqueId: 'T_MUSHINY_LATENT_ADAPTER_A_15',
        id: 15,
        state: VehicleUpgradeState.downloading,
      },
      {
        uniqueId: '2_latent',
        id: 2,
        state: VehicleUpgradeState.downloading,
      },
      {
        uniqueId: '3_latent',
        id: 3,
        state: VehicleUpgradeState.ready,
      },
      {
        uniqueId: '4_latent',
        id: 4,
        state: VehicleUpgradeState.ready,
      },
      {
        uniqueId: '5_latent',
        id: 5,
        state: VehicleUpgradeState.downloadFail,
      },
    ],
    hardware: 'AAA_5.1.1_pom',
    state: 'downloading',
    creatTime: '2022 10:11:11',
    creatUser: 'chengcheng.zhou',
    updateTime: '2022 12:11:11',
    updateUser: 'chengcheng.zhou',
  },
  {
    id: getRandomString(15),
    vehicles: [
      {
        uniqueId: '6_latent',
        id: 6,
        state: VehicleUpgradeState.ready,
      },
      {
        uniqueId: '7_latent',
        id: 7,
        state: VehicleUpgradeState.downloadFail,
      },
    ],
    hardware: 'BBB_5.1.1_pom',
    state: 'finished',
    creatTime: '2022 10:11:11',
    creatUser: 'chengcheng.zhou',
    updateTime: '2022 12:11:11',
    updateUser: 'chengcheng.zhou',
  },
];

// 资源绑定
export const ChargerGroupResource = [
  {
    groupName: '充电桩1',
    code: 'charger_group1',
  },
  {
    groupName: '充电桩2',
    code: 'charger_group2',
  },
  {
    groupName: '充电桩3',
    code: 'charger_group3',
  },
];

export const ResourceBindData = [
  {
    bindType: 'VEHICLE_TYPE',
    bindTypeName: '车类型',
    bindName: '分拣类型',
    bindCode: 'S_55_D_MUSHINY_SORTER_ADAPTER_T_sorter',
    resourceTypeName: '充电桩',
    resourceType: 'CHARGER_GROUP',
    resourceName: '充电桩1',
    resourceCode: 'charger_group1',
  },
  {
    bindType: 'VEHICLE_TYPE',
    bindTypeName: '车类型',
    bindName: '分拣类型',
    bindCode: 'S_55_D_MUSHINY_SORTER_ADAPTER_T_sorter',
    resourceTypeName: '充电桩',
    resourceType: 'CHARGER_GROUP',
    resourceName: '充电桩2',
    resourceCode: 'charger_group2',
  },
  {
    bindType: 'VEHICLE_TYPE',
    bindTypeName: '车类型',
    bindName: '分拣类型',
    bindCode: 'S_55_D_MUSHINY_SORTER_ADAPTER_T_sorter',
    resourceTypeName: '充电桩',
    resourceType: 'CHARGER_GROUP',
    resourceName: '充电桩3',
    resourceCode: 'charger_group3',
  },
];
